services:
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  
  rabbit-mq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  
networks:
  default:
    driver: bridge